apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
      annotations:
        linkerd.io/inject: enabled
        config.linkerd.io/proxy-cpu-request: 3m
        config.linkerd.io/proxy-memory-request: 17Mi
    spec:
      imagePullSecrets:
        - name: ghcr
      containers:
        - name: api
          image: busybox
          command:
            - /app/servicebin
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: 3m
              memory: 33Mi
            limits:
              cpu: "1"
              memory: 1Gi
          env:
            - name: HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  key: port
                  name: http
            - name: SERVICE_PARSER
              valueFrom:
                configMapKeyRef:
                  key: parser
                  name: service
            - name: SERVICE_USER
              valueFrom:
                configMapKeyRef:
                  key: user
                  name: service
            - name: SERVICE_BILLING
              valueFrom:
                configMapKeyRef:
                  key: billing
                  name: service
            - name: SERVICE_EXPORTER
              valueFrom:
                configMapKeyRef:
                  key: exporter
                  name: service
            - name: SERVICE_ORG
              valueFrom:
                configMapKeyRef:
                  key: org
                  name: service
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  key: url
                  name: redis
            - name: ROBOKASSA_WEBHOOKSECRET
              valueFrom:
                secretKeyRef:
                  key: webhooksecret
                  name: robokassa
            - name: LOGLEVEL
              value: error

---
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: api
