apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
      annotations:
        linkerd.io/inject: enabled
        config.linkerd.io/skip-outbound-ports: "4222"
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: api
          image: busybox
          command:
            - /app/servicebin
          lifecycle:
            preStop:
              exec:
                command:
                  - sh
                  - -c
                  - sleep 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
          env:
            - name: HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  key: port
                  name: http
            - name: SERVICE_PARSER
              valueFrom:
                configMapKeyRef:
                  key: parser
                  name: service
            - name: SERVICE_CITY
              valueFrom:
                configMapKeyRef:
                  key: city
                  name: service
            - name: SERVICE_CATEGORY
              valueFrom:
                configMapKeyRef:
                  key: category
                  name: service
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  key: url
                  name: redis
            - name: LOGLEVEL
              value: error
