name: release

on:
  release:
    types:
      - published

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: nnqq
          password: ${{ secrets.GH_CI_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/svc
          tag_with_ref: true
          build_args: GH_CI_TOKEN=${{ secrets.GH_CI_TOKEN }}

  deploy:
    needs:
      - push_to_registry
    name: Deploy to k8s
    runs-on: ubuntu-latest
    env:
      SERVICE_NAME: ${{github.repository}}#"nnqq/scr-"
    steps:
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_CI_TOKEN }}

    - name: Save DigitalOcean kubeconfig
      run: doctl kubernetes cluster kubeconfig save k8s

    - name: Apply deployment
      run: kubectl apply -f ${{ github.workspace }}/config/deployment.yml

    - name: Update deployment
      run: kubectl rollout restart deployment/$SERVICE_NAME

    - name: Verify deployment
      run: kubectl rollout status deployment/$SERVICE_NAME
